(cl:defpackage robot_control-srv
  (:use )
  (:export
   "DEFINEGLOBALPATH"
   "<DEFINEGLOBALPATH-REQUEST>"
   "DEFINEGLOBALPATH-REQUEST"
   "<DEFINEGLOBALPATH-RESPONSE>"
   "DEFINEGLOBALPATH-RESPONSE"
   "GETPOSITIONS"
   "<GETPOSITIONS-REQUEST>"
   "GETPOSITIONS-REQUEST"
   "<GETPOSITIONS-RESPONSE>"
   "GETPOSITIONS-RESPONSE"
   "ADDTOMAP"
   "<ADDTOMAP-REQUEST>"
   "ADDTOMAP-REQUEST"
   "<ADDTOMAP-RESPONSE>"
   "ADDTOMAP-RESPONSE"
  ))

