; Auto-generated. Do not edit!


(cl:in-package robot_control-msg)


;//! \htmlinclude createMapResult.msg.html

(cl:defclass <createMapResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass createMapResult (<createMapResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <createMapResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'createMapResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_control-msg:<createMapResult> is deprecated: use robot_control-msg:createMapResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <createMapResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_control-msg:success-val is deprecated.  Use robot_control-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <createMapResult>) ostream)
  "Serializes a message object of type '<createMapResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <createMapResult>) istream)
  "Deserializes a message object of type '<createMapResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<createMapResult>)))
  "Returns string type for a message object of type '<createMapResult>"
  "robot_control/createMapResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'createMapResult)))
  "Returns string type for a message object of type 'createMapResult"
  "robot_control/createMapResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<createMapResult>)))
  "Returns md5sum for a message object of type '<createMapResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'createMapResult)))
  "Returns md5sum for a message object of type 'createMapResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<createMapResult>)))
  "Returns full string definition for message of type '<createMapResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'createMapResult)))
  "Returns full string definition for message of type 'createMapResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <createMapResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <createMapResult>))
  "Converts a ROS message object to a list"
  (cl:list 'createMapResult
    (cl:cons ':success (success msg))
))
