; Auto-generated. Do not edit!


(cl:in-package robot_control-msg)


;//! \htmlinclude createMapGoal.msg.html

(cl:defclass <createMapGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass createMapGoal (<createMapGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <createMapGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'createMapGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_control-msg:<createMapGoal> is deprecated: use robot_control-msg:createMapGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <createMapGoal>) ostream)
  "Serializes a message object of type '<createMapGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <createMapGoal>) istream)
  "Deserializes a message object of type '<createMapGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<createMapGoal>)))
  "Returns string type for a message object of type '<createMapGoal>"
  "robot_control/createMapGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'createMapGoal)))
  "Returns string type for a message object of type 'createMapGoal"
  "robot_control/createMapGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<createMapGoal>)))
  "Returns md5sum for a message object of type '<createMapGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'createMapGoal)))
  "Returns md5sum for a message object of type 'createMapGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<createMapGoal>)))
  "Returns full string definition for message of type '<createMapGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'createMapGoal)))
  "Returns full string definition for message of type 'createMapGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <createMapGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <createMapGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'createMapGoal
))
