; Auto-generated. Do not edit!


(cl:in-package robot_control-msg)


;//! \htmlinclude searchGoal.msg.html

(cl:defclass <searchGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass searchGoal (<searchGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <searchGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'searchGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_control-msg:<searchGoal> is deprecated: use robot_control-msg:searchGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <searchGoal>) ostream)
  "Serializes a message object of type '<searchGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <searchGoal>) istream)
  "Deserializes a message object of type '<searchGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<searchGoal>)))
  "Returns string type for a message object of type '<searchGoal>"
  "robot_control/searchGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'searchGoal)))
  "Returns string type for a message object of type 'searchGoal"
  "robot_control/searchGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<searchGoal>)))
  "Returns md5sum for a message object of type '<searchGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'searchGoal)))
  "Returns md5sum for a message object of type 'searchGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<searchGoal>)))
  "Returns full string definition for message of type '<searchGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'searchGoal)))
  "Returns full string definition for message of type 'searchGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <searchGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <searchGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'searchGoal
))
