; Auto-generated. Do not edit!


(cl:in-package robot_control-msg)


;//! \htmlinclude searchFeedback.msg.html

(cl:defclass <searchFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass searchFeedback (<searchFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <searchFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'searchFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_control-msg:<searchFeedback> is deprecated: use robot_control-msg:searchFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <searchFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_control-msg:progress-val is deprecated.  Use robot_control-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <searchFeedback>) ostream)
  "Serializes a message object of type '<searchFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <searchFeedback>) istream)
  "Deserializes a message object of type '<searchFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<searchFeedback>)))
  "Returns string type for a message object of type '<searchFeedback>"
  "robot_control/searchFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'searchFeedback)))
  "Returns string type for a message object of type 'searchFeedback"
  "robot_control/searchFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<searchFeedback>)))
  "Returns md5sum for a message object of type '<searchFeedback>"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'searchFeedback)))
  "Returns md5sum for a message object of type 'searchFeedback"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<searchFeedback>)))
  "Returns full string definition for message of type '<searchFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'searchFeedback)))
  "Returns full string definition for message of type 'searchFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <searchFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <searchFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'searchFeedback
    (cl:cons ':progress (progress msg))
))
