// Generated by gencpp from file robot_control/addToMap.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ADDTOMAP_H
#define ROBOT_CONTROL_MESSAGE_ADDTOMAP_H

#include <ros/service_traits.h>


#include <robot_control/addToMapRequest.h>
#include <robot_control/addToMapResponse.h>


namespace robot_control
{

struct addToMap
{

typedef addToMapRequest Request;
typedef addToMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addToMap
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::addToMap > {
  static const char* value()
  {
    return "b0f29972a30c9830b340e4bab99692b0";
  }

  static const char* value(const ::robot_control::addToMap&) { return value(); }
};

template<>
struct DataType< ::robot_control::addToMap > {
  static const char* value()
  {
    return "robot_control/addToMap";
  }

  static const char* value(const ::robot_control::addToMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::addToMapRequest> should match 
// service_traits::MD5Sum< ::robot_control::addToMap > 
template<>
struct MD5Sum< ::robot_control::addToMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::addToMap >::value();
  }
  static const char* value(const ::robot_control::addToMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::addToMapRequest> should match 
// service_traits::DataType< ::robot_control::addToMap > 
template<>
struct DataType< ::robot_control::addToMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::addToMap >::value();
  }
  static const char* value(const ::robot_control::addToMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::addToMapResponse> should match 
// service_traits::MD5Sum< ::robot_control::addToMap > 
template<>
struct MD5Sum< ::robot_control::addToMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::addToMap >::value();
  }
  static const char* value(const ::robot_control::addToMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::addToMapResponse> should match 
// service_traits::DataType< ::robot_control::addToMap > 
template<>
struct DataType< ::robot_control::addToMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::addToMap >::value();
  }
  static const char* value(const ::robot_control::addToMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ADDTOMAP_H
