// Generated by gencpp from file robot_control/addToMapResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ADDTOMAPRESPONSE_H
#define ROBOT_CONTROL_MESSAGE_ADDTOMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct addToMapResponse_
{
  typedef addToMapResponse_<ContainerAllocator> Type;

  addToMapResponse_()
    : added(false)  {
    }
  addToMapResponse_(const ContainerAllocator& _alloc)
    : added(false)  {
    }



   typedef uint8_t _added_type;
  _added_type added;




  typedef boost::shared_ptr< ::robot_control::addToMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::addToMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addToMapResponse_

typedef ::robot_control::addToMapResponse_<std::allocator<void> > addToMapResponse;

typedef boost::shared_ptr< ::robot_control::addToMapResponse > addToMapResponsePtr;
typedef boost::shared_ptr< ::robot_control::addToMapResponse const> addToMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::addToMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::addToMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::addToMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::addToMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::addToMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::addToMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::addToMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::addToMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::addToMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db18cd4751bf648d25e6235126cead94";
  }

  static const char* value(const ::robot_control::addToMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb18cd4751bf648dULL;
  static const uint64_t static_value2 = 0x25e6235126cead94ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::addToMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/addToMapResponse";
  }

  static const char* value(const ::robot_control::addToMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::addToMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool added\n\
";
  }

  static const char* value(const ::robot_control::addToMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::addToMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.added);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct addToMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::addToMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::addToMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "added: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.added);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ADDTOMAPRESPONSE_H
