// Generated by gencpp from file robot_control/addToMapRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ADDTOMAPREQUEST_H
#define ROBOT_CONTROL_MESSAGE_ADDTOMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct addToMapRequest_
{
  typedef addToMapRequest_<ContainerAllocator> Type;

  addToMapRequest_()
    : start_x(0.0)
    , start_y(0.0)
    , wall_x(0.0)
    , wall_y(0.0)
    , inc_x(0.0)
    , inc_y(0.0)
    , range(0.0)  {
    }
  addToMapRequest_(const ContainerAllocator& _alloc)
    : start_x(0.0)
    , start_y(0.0)
    , wall_x(0.0)
    , wall_y(0.0)
    , inc_x(0.0)
    , inc_y(0.0)
    , range(0.0)  {
    }



   typedef double _start_x_type;
  _start_x_type start_x;

   typedef double _start_y_type;
  _start_y_type start_y;

   typedef double _wall_x_type;
  _wall_x_type wall_x;

   typedef double _wall_y_type;
  _wall_y_type wall_y;

   typedef double _inc_x_type;
  _inc_x_type inc_x;

   typedef double _inc_y_type;
  _inc_y_type inc_y;

   typedef double _range_type;
  _range_type range;




  typedef boost::shared_ptr< ::robot_control::addToMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::addToMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addToMapRequest_

typedef ::robot_control::addToMapRequest_<std::allocator<void> > addToMapRequest;

typedef boost::shared_ptr< ::robot_control::addToMapRequest > addToMapRequestPtr;
typedef boost::shared_ptr< ::robot_control::addToMapRequest const> addToMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::addToMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::addToMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::addToMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::addToMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::addToMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::addToMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::addToMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::addToMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::addToMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4342df1428001f4b7aff723e4008c5a5";
  }

  static const char* value(const ::robot_control::addToMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4342df1428001f4bULL;
  static const uint64_t static_value2 = 0x7aff723e4008c5a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::addToMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/addToMapRequest";
  }

  static const char* value(const ::robot_control::addToMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::addToMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 start_x\n\
float64 start_y\n\
float64 wall_x\n\
float64 wall_y\n\
float64 inc_x\n\
float64 inc_y\n\
float64 range\n\
";
  }

  static const char* value(const ::robot_control::addToMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::addToMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_x);
      stream.next(m.start_y);
      stream.next(m.wall_x);
      stream.next(m.wall_y);
      stream.next(m.inc_x);
      stream.next(m.inc_y);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct addToMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::addToMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::addToMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "start_x: ";
    Printer<double>::stream(s, indent + "  ", v.start_x);
    s << indent << "start_y: ";
    Printer<double>::stream(s, indent + "  ", v.start_y);
    s << indent << "wall_x: ";
    Printer<double>::stream(s, indent + "  ", v.wall_x);
    s << indent << "wall_y: ";
    Printer<double>::stream(s, indent + "  ", v.wall_y);
    s << indent << "inc_x: ";
    Printer<double>::stream(s, indent + "  ", v.inc_x);
    s << indent << "inc_y: ";
    Printer<double>::stream(s, indent + "  ", v.inc_y);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ADDTOMAPREQUEST_H
