// Generated by gencpp from file robot_control/createMap.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_CREATEMAP_H
#define ROBOT_CONTROL_MESSAGE_CREATEMAP_H

#include <ros/service_traits.h>


#include <robot_control/createMapRequest.h>
#include <robot_control/createMapResponse.h>


namespace robot_control
{

struct createMap
{

typedef createMapRequest Request;
typedef createMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct createMap
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::createMap > {
  static const char* value()
  {
    return "8e5036d42e3183a686cafeab6c2d9883";
  }

  static const char* value(const ::robot_control::createMap&) { return value(); }
};

template<>
struct DataType< ::robot_control::createMap > {
  static const char* value()
  {
    return "robot_control/createMap";
  }

  static const char* value(const ::robot_control::createMap&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::createMapRequest> should match 
// service_traits::MD5Sum< ::robot_control::createMap > 
template<>
struct MD5Sum< ::robot_control::createMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::createMap >::value();
  }
  static const char* value(const ::robot_control::createMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::createMapRequest> should match 
// service_traits::DataType< ::robot_control::createMap > 
template<>
struct DataType< ::robot_control::createMapRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::createMap >::value();
  }
  static const char* value(const ::robot_control::createMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::createMapResponse> should match 
// service_traits::MD5Sum< ::robot_control::createMap > 
template<>
struct MD5Sum< ::robot_control::createMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::createMap >::value();
  }
  static const char* value(const ::robot_control::createMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::createMapResponse> should match 
// service_traits::DataType< ::robot_control::createMap > 
template<>
struct DataType< ::robot_control::createMapResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::createMap >::value();
  }
  static const char* value(const ::robot_control::createMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_CREATEMAP_H
