// Generated by gencpp from file robot_control/defineGlobalPathResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATHRESPONSE_H
#define ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct defineGlobalPathResponse_
{
  typedef defineGlobalPathResponse_<ContainerAllocator> Type;

  defineGlobalPathResponse_()
    : x_path()
    , y_path()  {
    }
  defineGlobalPathResponse_(const ContainerAllocator& _alloc)
    : x_path(_alloc)
    , y_path(_alloc)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_path_type;
  _x_path_type x_path;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_path_type;
  _y_path_type y_path;




  typedef boost::shared_ptr< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct defineGlobalPathResponse_

typedef ::robot_control::defineGlobalPathResponse_<std::allocator<void> > defineGlobalPathResponse;

typedef boost::shared_ptr< ::robot_control::defineGlobalPathResponse > defineGlobalPathResponsePtr;
typedef boost::shared_ptr< ::robot_control::defineGlobalPathResponse const> defineGlobalPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::defineGlobalPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f5810bf16ed1930681a0f067d3142cf";
  }

  static const char* value(const ::robot_control::defineGlobalPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f5810bf16ed1930ULL;
  static const uint64_t static_value2 = 0x681a0f067d3142cfULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/defineGlobalPathResponse";
  }

  static const char* value(const ::robot_control::defineGlobalPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x_path\n\
float64[] y_path\n\
";
  }

  static const char* value(const ::robot_control::defineGlobalPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_path);
      stream.next(m.y_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct defineGlobalPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::defineGlobalPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::defineGlobalPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "x_path[]" << std::endl;
    for (size_t i = 0; i < v.x_path.size(); ++i)
    {
      s << indent << "  x_path[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x_path[i]);
    }
    s << indent << "y_path[]" << std::endl;
    for (size_t i = 0; i < v.y_path.size(); ++i)
    {
      s << indent << "  y_path[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y_path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATHRESPONSE_H
