// Generated by gencpp from file robot_control/defineGlobalPath.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATH_H
#define ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATH_H

#include <ros/service_traits.h>


#include <robot_control/defineGlobalPathRequest.h>
#include <robot_control/defineGlobalPathResponse.h>


namespace robot_control
{

struct defineGlobalPath
{

typedef defineGlobalPathRequest Request;
typedef defineGlobalPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct defineGlobalPath
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::defineGlobalPath > {
  static const char* value()
  {
    return "4fe135cc34bd036b473beef806eb4cd1";
  }

  static const char* value(const ::robot_control::defineGlobalPath&) { return value(); }
};

template<>
struct DataType< ::robot_control::defineGlobalPath > {
  static const char* value()
  {
    return "robot_control/defineGlobalPath";
  }

  static const char* value(const ::robot_control::defineGlobalPath&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::defineGlobalPathRequest> should match 
// service_traits::MD5Sum< ::robot_control::defineGlobalPath > 
template<>
struct MD5Sum< ::robot_control::defineGlobalPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::defineGlobalPath >::value();
  }
  static const char* value(const ::robot_control::defineGlobalPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::defineGlobalPathRequest> should match 
// service_traits::DataType< ::robot_control::defineGlobalPath > 
template<>
struct DataType< ::robot_control::defineGlobalPathRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::defineGlobalPath >::value();
  }
  static const char* value(const ::robot_control::defineGlobalPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::defineGlobalPathResponse> should match 
// service_traits::MD5Sum< ::robot_control::defineGlobalPath > 
template<>
struct MD5Sum< ::robot_control::defineGlobalPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::defineGlobalPath >::value();
  }
  static const char* value(const ::robot_control::defineGlobalPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::defineGlobalPathResponse> should match 
// service_traits::DataType< ::robot_control::defineGlobalPath > 
template<>
struct DataType< ::robot_control::defineGlobalPathResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::defineGlobalPath >::value();
  }
  static const char* value(const ::robot_control::defineGlobalPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_DEFINEGLOBALPATH_H
