// Generated by gencpp from file robot_control/getPositionsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_GETPOSITIONSRESPONSE_H
#define ROBOT_CONTROL_MESSAGE_GETPOSITIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct getPositionsResponse_
{
  typedef getPositionsResponse_<ContainerAllocator> Type;

  getPositionsResponse_()
    : x()
    , y()
    , id(0)  {
    }
  getPositionsResponse_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , id(0)  {
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;

   typedef int32_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::robot_control::getPositionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::getPositionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getPositionsResponse_

typedef ::robot_control::getPositionsResponse_<std::allocator<void> > getPositionsResponse;

typedef boost::shared_ptr< ::robot_control::getPositionsResponse > getPositionsResponsePtr;
typedef boost::shared_ptr< ::robot_control::getPositionsResponse const> getPositionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::getPositionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::getPositionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::getPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::getPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::getPositionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::getPositionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::getPositionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::getPositionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::getPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "effd48c094c155513beedf458b8e9089";
  }

  static const char* value(const ::robot_control::getPositionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeffd48c094c15551ULL;
  static const uint64_t static_value2 = 0x3beedf458b8e9089ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::getPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/getPositionsResponse";
  }

  static const char* value(const ::robot_control::getPositionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::getPositionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n\
float64[] y\n\
int32 id\n\
";
  }

  static const char* value(const ::robot_control::getPositionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::getPositionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct getPositionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::getPositionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::getPositionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_GETPOSITIONSRESPONSE_H
