// Generated by gencpp from file robot_control/getPositions.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_GETPOSITIONS_H
#define ROBOT_CONTROL_MESSAGE_GETPOSITIONS_H

#include <ros/service_traits.h>


#include <robot_control/getPositionsRequest.h>
#include <robot_control/getPositionsResponse.h>


namespace robot_control
{

struct getPositions
{

typedef getPositionsRequest Request;
typedef getPositionsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getPositions
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::getPositions > {
  static const char* value()
  {
    return "70953a0a6fffaa23e9167aef60c438f9";
  }

  static const char* value(const ::robot_control::getPositions&) { return value(); }
};

template<>
struct DataType< ::robot_control::getPositions > {
  static const char* value()
  {
    return "robot_control/getPositions";
  }

  static const char* value(const ::robot_control::getPositions&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::getPositionsRequest> should match 
// service_traits::MD5Sum< ::robot_control::getPositions > 
template<>
struct MD5Sum< ::robot_control::getPositionsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::getPositions >::value();
  }
  static const char* value(const ::robot_control::getPositionsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::getPositionsRequest> should match 
// service_traits::DataType< ::robot_control::getPositions > 
template<>
struct DataType< ::robot_control::getPositionsRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::getPositions >::value();
  }
  static const char* value(const ::robot_control::getPositionsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::getPositionsResponse> should match 
// service_traits::MD5Sum< ::robot_control::getPositions > 
template<>
struct MD5Sum< ::robot_control::getPositionsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::getPositions >::value();
  }
  static const char* value(const ::robot_control::getPositionsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::getPositionsResponse> should match 
// service_traits::DataType< ::robot_control::getPositions > 
template<>
struct DataType< ::robot_control::getPositionsResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::getPositions >::value();
  }
  static const char* value(const ::robot_control::getPositionsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_GETPOSITIONS_H
