// Generated by gencpp from file robot_control/laserMeasures.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_LASERMEASURES_H
#define ROBOT_CONTROL_MESSAGE_LASERMEASURES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_control
{
template <class ContainerAllocator>
struct laserMeasures_
{
  typedef laserMeasures_<ContainerAllocator> Type;

  laserMeasures_()
    : header()
    , range()
    , angle()
    , front(0.0)  {
    }
  laserMeasures_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range(_alloc)
    , angle(_alloc)
    , front(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _range_type;
  _range_type range;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angle_type;
  _angle_type angle;

   typedef double _front_type;
  _front_type front;




  typedef boost::shared_ptr< ::robot_control::laserMeasures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::laserMeasures_<ContainerAllocator> const> ConstPtr;

}; // struct laserMeasures_

typedef ::robot_control::laserMeasures_<std::allocator<void> > laserMeasures;

typedef boost::shared_ptr< ::robot_control::laserMeasures > laserMeasuresPtr;
typedef boost::shared_ptr< ::robot_control::laserMeasures const> laserMeasuresConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::laserMeasures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::laserMeasures_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::laserMeasures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::laserMeasures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::laserMeasures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::laserMeasures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::laserMeasures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::laserMeasures_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::laserMeasures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b95a89dd4dc981e642360131c830c02";
  }

  static const char* value(const ::robot_control::laserMeasures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b95a89dd4dc981eULL;
  static const uint64_t static_value2 = 0x642360131c830c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::laserMeasures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/laserMeasures";
  }

  static const char* value(const ::robot_control::laserMeasures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::laserMeasures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] range\n\
float64[] angle\n\
float64 front\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robot_control::laserMeasures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::laserMeasures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range);
      stream.next(m.angle);
      stream.next(m.front);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct laserMeasures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::laserMeasures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::laserMeasures_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range[]" << std::endl;
    for (size_t i = 0; i < v.range.size(); ++i)
    {
      s << indent << "  range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.range[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "front: ";
    Printer<double>::stream(s, indent + "  ", v.front);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_LASERMEASURES_H
