// Generated by gencpp from file robot_control/NavigationDriveServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_NAVIGATIONDRIVESERVICERESPONSE_H
#define ROBOT_CONTROL_MESSAGE_NAVIGATIONDRIVESERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct NavigationDriveServiceResponse_
{
  typedef NavigationDriveServiceResponse_<ContainerAllocator> Type;

  NavigationDriveServiceResponse_()
    : end(false)  {
    }
  NavigationDriveServiceResponse_(const ContainerAllocator& _alloc)
    : end(false)  {
    }



   typedef uint8_t _end_type;
  _end_type end;




  typedef boost::shared_ptr< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationDriveServiceResponse_

typedef ::robot_control::NavigationDriveServiceResponse_<std::allocator<void> > NavigationDriveServiceResponse;

typedef boost::shared_ptr< ::robot_control::NavigationDriveServiceResponse > NavigationDriveServiceResponsePtr;
typedef boost::shared_ptr< ::robot_control::NavigationDriveServiceResponse const> NavigationDriveServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9ac4e286e7f89fc602116455cd26e68";
  }

  static const char* value(const ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9ac4e286e7f89fcULL;
  static const uint64_t static_value2 = 0x602116455cd26e68ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/NavigationDriveServiceResponse";
  }

  static const char* value(const ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool end\n\
";
  }

  static const char* value(const ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct NavigationDriveServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::NavigationDriveServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "end: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_NAVIGATIONDRIVESERVICERESPONSE_H
