// Generated by gencpp from file robot_control/search.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_SEARCH_H
#define ROBOT_CONTROL_MESSAGE_SEARCH_H

#include <ros/service_traits.h>


#include <robot_control/searchRequest.h>
#include <robot_control/searchResponse.h>


namespace robot_control
{

struct search
{

typedef searchRequest Request;
typedef searchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct search
} // namespace robot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_control::search > {
  static const char* value()
  {
    return "8e5036d42e3183a686cafeab6c2d9883";
  }

  static const char* value(const ::robot_control::search&) { return value(); }
};

template<>
struct DataType< ::robot_control::search > {
  static const char* value()
  {
    return "robot_control/search";
  }

  static const char* value(const ::robot_control::search&) { return value(); }
};


// service_traits::MD5Sum< ::robot_control::searchRequest> should match 
// service_traits::MD5Sum< ::robot_control::search > 
template<>
struct MD5Sum< ::robot_control::searchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::search >::value();
  }
  static const char* value(const ::robot_control::searchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::searchRequest> should match 
// service_traits::DataType< ::robot_control::search > 
template<>
struct DataType< ::robot_control::searchRequest>
{
  static const char* value()
  {
    return DataType< ::robot_control::search >::value();
  }
  static const char* value(const ::robot_control::searchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_control::searchResponse> should match 
// service_traits::MD5Sum< ::robot_control::search > 
template<>
struct MD5Sum< ::robot_control::searchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_control::search >::value();
  }
  static const char* value(const ::robot_control::searchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_control::searchResponse> should match 
// service_traits::DataType< ::robot_control::search > 
template<>
struct DataType< ::robot_control::searchResponse>
{
  static const char* value()
  {
    return DataType< ::robot_control::search >::value();
  }
  static const char* value(const ::robot_control::searchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_SEARCH_H
