// Generated by gencpp from file robot_control/searchResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_SEARCHRESPONSE_H
#define ROBOT_CONTROL_MESSAGE_SEARCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_control
{
template <class ContainerAllocator>
struct searchResponse_
{
  typedef searchResponse_<ContainerAllocator> Type;

  searchResponse_()
    : knowledge(0.0)  {
    }
  searchResponse_(const ContainerAllocator& _alloc)
    : knowledge(0.0)  {
    }



   typedef float _knowledge_type;
  _knowledge_type knowledge;




  typedef boost::shared_ptr< ::robot_control::searchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::searchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct searchResponse_

typedef ::robot_control::searchResponse_<std::allocator<void> > searchResponse;

typedef boost::shared_ptr< ::robot_control::searchResponse > searchResponsePtr;
typedef boost::shared_ptr< ::robot_control::searchResponse const> searchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::searchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::searchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot_control': ['/home/rafael/SORS_Application/src/robot_control/msg', '/home/rafael/SORS_Application/devel/share/robot_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::searchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::searchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::searchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::searchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::searchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::searchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::searchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e5036d42e3183a686cafeab6c2d9883";
  }

  static const char* value(const ::robot_control::searchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e5036d42e3183a6ULL;
  static const uint64_t static_value2 = 0x86cafeab6c2d9883ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::searchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/searchResponse";
  }

  static const char* value(const ::robot_control::searchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::searchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 knowledge\n\
";
  }

  static const char* value(const ::robot_control::searchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::searchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.knowledge);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct searchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::searchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::searchResponse_<ContainerAllocator>& v)
  {
    s << indent << "knowledge: ";
    Printer<float>::stream(s, indent + "  ", v.knowledge);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_SEARCHRESPONSE_H
